Increase `ReservedCodeCacheSize` to 50m (#97)
The default is set to `3m`. We have found that Pkl can see the
following exceptions, with the root cause being new code in the
`org.pkl.core.ast.builder.AstBuilder` class.

Exception snippet
-----------------

```
Exception in thread "main" java.lang.InternalError: java.lang.VirtualMachineError: Out of space in CodeCache for adapters
...
...
Exception: java.lang.VirtualMachineError thrown from the UncaughtExceptionHandler in thread "main"
Failed processing PKL configuration with entrypoint(s) 'i4c/teams/mail/output.pkl' (PWD: /runner/build/6d00ecfba6218881/root):
[3.690s][warning][codecache] CodeCache is full. Compiler has been disabled.
[3.690s][warning][codecache] Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=3392Kb used=3370Kb max_used=3377Kb free=21Kb
 bounds [0x00007f3b5cc91000, 0x00007f3b5cfe1000, 0x00007f3b5cfe1000]
 total_blobs=1576 nmethods=985 adapters=498
 compilation: disabled (not enough contiguous free space left)
              stopped_count=1, restarted_count=0
 full_count=1
```